---
title: "R Notebook"
output: Box Crab
---

Goal: pull data about flamed box crab and compile it to one data table.

```{r setup}
load("glf_reduced.RData")
load("seus_reduced.RData")
load("neus_reduced.RData")
load("GSDET_CAT_INF_SPE_merge.RData")

library(dplyr)
library(data.table)
library(stringr)
library(tibble)

capitalize <- function(x){
first <- toupper(substr(x, start=1, stop=1)) ## capitalize first letter
rest <- tolower(substr(x, start=2, stop=nchar(x)))## everything else lowercase
paste0(first, rest)
}
```

Make spelling edits to Gulf data
```{r spelling}
glf_reduced.dt$SPEC_GLF <- str_replace_all(glf_reduced.dt$SPEC_GLF, "FLAMME", "FLAMMEA")
```

Extract relavent data.
```{r extraction}
glf_boxcrab <- subset(glf_reduced.dt, SPEC_GLF == "FLAMMEA")
seus_boxcrab <- subset(seus_reduced, SPECIESSCIENTIFICNAME.x == "CALAPPA FLAMMEA")
neus_boxcrab <- subset(neus_reduced, SCINAME == "CALAPPA FLAMMEA")
```

Reduce datasets to have same data.
```{r reduce}
glf_boxcrab_red <- glf_boxcrab[, c("LEN_GLF", "SEX_GLF", "MO_DAY_YR", "TEMP_BOT", "DECSLAT", "DECSLON")]
seus_boxcrab <- as.data.table(seus_boxcrab)
seus_boxcrab_red <- seus_boxcrab[, c("DATE.x", "SPECIESSCIENTIFICNAME.x", "SPECIESCOMMONNAME.x", "TEMPBOTTOM.x", "LATITUDESTART.x", "LONGITUDESTART", "LEN1", "SEXDESCRIPTION")]
neus_boxcrab_red <- neus_boxcrab[, c("CATCHSEX", "LAT", "LON", "EST_TOWDATE", "BOTTEMP", "LENGTH", "SCINAME", "COMNAME")]
```

Add and rename columns so they can bind.
```{r add and rename}
glf_boxcrab_red <- add_column(glf_boxcrab_red, SCINAME = "Calappa flammea")
glf_boxcrab_red <- add_column(glf_boxcrab_red, COMNAME = "Flame box crab")
glf_boxcrab_red <- rename(glf_boxcrab_red, "LENGTH" = "LEN_GLF", "SEX" = "SEX_GLF", "TEMPERATURE" = "TEMP_BOT", "LATITUDE" = "DECSLAT", "LONGITUDE" = "DECSLON", "DATE" = "MO_DAY_YR")
seus_boxcrab_red <- rename(seus_boxcrab_red, "DATE" = "DATE.x", "SCINAME" = "SPECIESSCIENTIFICNAME.x", "COMNAME" = "SPECIESCOMMONNAME.x", "TEMPERATURE" = "TEMPBOTTOM.x", "LATITUDE" = "LATITUDESTART.x", "LONGITUDE" = "LONGITUDESTART", "LENGTH" = "LEN1", "SEX" = "SEXDESCRIPTION")
seus_boxcrab_red$SCINAME <- capitalize(seus_boxcrab_red$SCINAME)
seus_boxcrab_red$COMNAME <- capitalize(seus_boxcrab_red$COMNAME)
neus_boxcrab_red <- rename(neus_boxcrab_red, "SEX" = "CATCHSEX", "LATITUDE" = "LAT", "LONGITUDE" = "LON", "DATE" = "EST_TOWDATE", "TEMPERATURE" = "BOTTEMP")
neus_boxcrab_red$SCINAME <- as.character(neus_boxcrab_red$SCINAME)
neus_boxcrab_red$SCINAME <- capitalize(neus_boxcrab_red$SCINAME)
neus_boxcrab_red$COMNAME <- as.character(neus_boxcrab_red$COMNAME)
neus_boxcrab_red$COMNAME <- capitalize(neus_boxcrab_red$COMNAME)
```

Reorder columns so they can bind.
```{r reorder}
glf_boxcrab_red <- glf_boxcrab_red[,c("SCINAME", "COMNAME", "LENGTH", "SEX", "LATITUDE", "LONGITUDE", "TEMPERATURE", "DATE")]
seus_boxcrab_red <- as.data.frame(seus_boxcrab_red)
seus_boxcrab_red <- seus_boxcrab_red[,c("SCINAME", "COMNAME", "LENGTH", "SEX", "LATITUDE", "LONGITUDE", "TEMPERATURE", "DATE")]
neus_boxcrab_red <- neus_boxcrab_red[,c("SCINAME", "COMNAME", "LENGTH", "SEX", "LATITUDE", "LONGITUDE", "TEMPERATURE", "DATE")]
seus_boxcrab_red <- seus_boxcrab_red[,c("SCINAME", "COMNAME", "LENGTH", "SEX", "LATITUDE", "LONGITUDE", "TEMPERATURE", "DATE")]
neus_boxcrab_red <- neus_boxcrab_red[,c("SCINAME", "COMNAME", "LENGTH", "SEX", "LATITUDE", "LONGITUDE", "TEMPERATURE", "DATE")]
```

Fix classes
```{r classes}
seus_boxcrab_red$LENGTH <- as.numeric(seus_boxcrab_red$LENGTH)
seus_boxcrab_red$LATITUDE <- as.numeric(seus_boxcrab_red$LATITUDE)
seus_boxcrab_red$LONGITUDE <- as.numeric(seus_boxcrab_red$LONGITUDE)
seus_boxcrab_red$TEMPERATURE <- as.numeric(seus_boxcrab_red$TEMPERATURE)
seus_boxcrab_red$DATE <- as.Date(seus_boxcrab_red$DATE, format = "%m-%d-%Y")
neus_boxcrab_red$LENGTH <- as.numeric(neus_boxcrab_red$LENGTH)
neus_boxcrab_red$LATITUDE <- as.numeric(neus_boxcrab_red$LATITUDE)
neus_boxcrab_red$LONGITUDE <- as.numeric(neus_boxcrab_red$LONGITUDE)
neus_boxcrab_red$TEMPERATURE <- as.numeric(neus_boxcrab_red$TEMPERATURE)
neus_boxcrab_red$DATE <- as.Date(neus_boxcrab_red$DATE)
```

Bind tables.
```{r bind}
glf_boxcrab_red.dt <- as.data.table(glf_boxcrab_red)
seus_boxcrab_red.dt <- as.data.table(seus_boxcrab_red)
neus_boxcrab_red.dt <- as.data.table(neus_boxcrab_red)
boxcrab_table <- rbind(glf_boxcrab_red, neus_boxcrab_red, seus_boxcrab_red)
```
