---
title: "Lab Notebook"
output: html_notebook
---
**September 13, 2019**

* completed learning contract [learning contract](https://docs.google.com/document/d/18EuaptJ0LtB-4bw0Bqum4cfWjOU25bCIm0ezJRgJDqY/edit)
* talked about project timeline/goals
* setup GitHub account [GitHub](https://github.com)
* downloaded R and RStudio
* read Marine Taxa Track Local Climate Velocities
* 3 hours

*****

**September 20, 2019**

* outlined timeline for both semesters [outline](file:///Users/ria/Desktop/R/TraitVariability_EastCoast/OurPlan_19_20.nb.html)
* first proposal ~October 18
* practiced with swirl
* began doc to collect relevant artices
* 3.5 hours

*****

**September 26, 2019**

* lab meeting
* 1 hour

*****

**September 27, 2019**

* practiced R via swirl
* started reading papers for background info
* will write background together
* 3 hours

*****

**October 1, 2019**

* outlined backgroup section of research paper
* began 1st draft of paper [draft](https://docs.google.com/document/d/1oV0CoRcHu2-kNr2E14lT6bcgtEkBZnjOnXEybTrJRjg/edit)
* have background done in ~1.5 weeks
* 3.5 hours

*****

**October 3, 2019**

* lab meeting
* importance of visuals when conveying information
* 1 hour

*****

**October 10, 2019**

* lab meeting
* colonization seems to be predicted by bottom temps!
* 1 hour

*****

**October 11, 2019**

* continue to work on proposal background
* readings on spatial sorting
* 3 hours

*****

**October 17, 2019**

* lab meeting
* predictions of coral cover
* 1 hour

*****

**October 18, 2019**

* finishing up first draft of background
* beginning collecting data next week!
* 3 hours

*****

**October 24, 2019**

* review postdoc application
* 1 hour

*****

**October 25, 2019**

* went over background revisions
* started looking at trawl data sets
* research to decipher column names
* starting revising background
* 3 hours

*****

**October 31,2019**

* HALLOWEEN
* lab meeting
* 1 hour

******

**November 1, 2019**

* lots of work on background
* kind of started tutorial
* 3 hours

*****

**November 7, 2019**

* OceanAdapt discussion
* 1 hour

*****

**November 10, 2019**

* more struggle with tutorial
* more background progress
* 3 hours

*****

**November 14, 2019**

* lab meeting
* 1 hour

*****

**November 15, 2019**

* success with tutorial!
* moved files to correct location
* discussed upcoming work
* began finding column names
* 3 hours

*****

**November 21, 2019**

* posting code with published work
* "release"
* 1 hour

*****

**November 22, 2019**

* basically finished with column names, at least what is possible
* figuring out which columns to use
* 3 hours

*****

**November 26, 2019**

* finished background (draft 2)
* neus full (success!!)
* 3 hours

*****

**December 5, 2019**

* clownfish carol
* 1 hour

*****

**December 6, 2019**

* picking comlunms
* glf_full
* starting to delete columns
* 3 hours

*****

**December 12, 2019**

* final touches on paper
* last lab meeting
* 2 hours

*****

**Decemebr 13, 2019**

* semester debrief
* reduced data from 3 locations
* 4 hours

*****

**January 29, 2020**

* lab meeting
* 1 hour

*****

**January 30, 2020**

* first day!!
* writing code for reduced and merged data tables
* stuck on GLF, "vector memory exhausted"
* 3 hours

******

**February 5, 2020**

* lab meeting
* 1 hour

*****

**February 6, 2020**

* the memory exhaustion struggle continues
* going to Tuckerton March 25th
* almost finished with data reduction code
* figuring out Scotian data
* will move on to some lit reviews next week