---
title: "R Notebook"
output: Lookdown
---

Goal: pull data about lookdown and compile it to one data table.

```{r setup}
load("glf_reduced.RData")
load("seus_reduced.RData")
load("neus_reduced.RData")
load("GSDET_CAT_INF_SPE_merge.RData")

library(dplyr)
library(data.table)
library(stringr)
library(tibble)

capitalize <- function(x){
first <- toupper(substr(x, start=1, stop=1)) ## capitalize first letter
rest <- tolower(substr(x, start=2, stop=nchar(x)))## everything else lowercase
paste0(first, rest)
}
```

Extract relavent data.
```{r extraction}
glf_lookdown <- subset(glf_reduced.dt, SPEC_GLF == "VOMER")
seus_lookdown <- subset(seus_reduced, SPECIESSCIENTIFICNAME.x == "SELENE VOMER")
neus_lookdown <- subset(neus_reduced, SCINAME == "SELENE VOMER")
```

Reduce datasets to have same data.
```{r reduce}
glf_lookdown_red <- glf_lookdown[, c("LEN_GLF", "SEX_GLF", "MO_DAY_YR", "TEMP_BOT", "DECSLAT", "DECSLON")]
seus_lookdown <- as.data.table(seus_lookdown)
seus_lookdown_red <- seus_lookdown[, c("DATE.x", "SPECIESSCIENTIFICNAME.x", "SPECIESCOMMONNAME.x", "TEMPBOTTOM.x", "LATITUDESTART.x", "LONGITUDESTART", "LEN1", "SEXDESCRIPTION")]
neus_lookdown_red <- neus_lookdown[, c("CATCHSEX", "LAT", "LON", "EST_TOWDATE", "BOTTEMP", "LENGTH", "SCINAME", "COMNAME")]
```

Add and rename columns so they can bind.
```{r add and rename}
glf_lookdown_red <- add_column(glf_lookdown_red, SCINAME = "Selene vomer")
glf_lookdown_red <- add_column(glf_lookdown_red, COMNAME = "Lookdown")
glf_lookdown_red <- rename(glf_lookdown_red, "LENGTH" = "LEN_GLF", "SEX" = "SEX_GLF", "TEMPERATURE" = "TEMP_BOT", "LATITUDE" = "DECSLAT", "LONGITUDE" = "DECSLON", "DATE" = "MO_DAY_YR")
seus_lookdown_red <- rename(seus_lookdown_red, "DATE" = "DATE.x", "SCINAME" = "SPECIESSCIENTIFICNAME.x", "COMNAME" = "SPECIESCOMMONNAME.x", "TEMPERATURE" = "TEMPBOTTOM.x", "LATITUDE" = "LATITUDESTART.x", "LONGITUDE" = "LONGITUDESTART", "LENGTH" = "LEN1", "SEX" = "SEXDESCRIPTION")
seus_lookdown_red$SCINAME <- capitalize(seus_lookdown_red$SCINAME)
seus_lookdown_red$COMNAME <- capitalize(seus_lookdown_red$COMNAME)
neus_lookdown_red <- rename(neus_lookdown_red, "SEX" = "CATCHSEX", "LATITUDE" = "LAT", "LONGITUDE" = "LON", "DATE" = "EST_TOWDATE", "TEMPERATURE" = "BOTTEMP")
neus_lookdown_red$SCINAME <- as.character(neus_lookdown_red$SCINAME)
neus_lookdown_red$SCINAME <- capitalize(neus_lookdown_red$SCINAME)
neus_lookdown_red$COMNAME <- as.character(neus_lookdown_red$COMNAME)
neus_lookdown_red$COMNAME <- capitalize(neus_lookdown_red$COMNAME)
```

Reorder columns so they can bind.
```{r reorder}
glf_lookdown_red <- glf_lookdown_red[,c("SCINAME", "COMNAME", "LENGTH", "SEX", "LATITUDE", "LONGITUDE", "TEMPERATURE", "DATE")]
seus_lookdown_red <- as.data.frame(seus_lookdown_red)
seus_lookdown_red <- seus_lookdown_red[,c("SCINAME", "COMNAME", "LENGTH", "SEX", "LATITUDE", "LONGITUDE", "TEMPERATURE", "DATE")]
neus_lookdown_red <- neus_lookdown_red[,c("SCINAME", "COMNAME", "LENGTH", "SEX", "LATITUDE", "LONGITUDE", "TEMPERATURE", "DATE")]
seus_lookdown_red <- seus_lookdown_red[,c("SCINAME", "COMNAME", "LENGTH", "SEX", "LATITUDE", "LONGITUDE", "TEMPERATURE", "DATE")]
neus_lookdown_red <- neus_lookdown_red[,c("SCINAME", "COMNAME", "LENGTH", "SEX", "LATITUDE", "LONGITUDE", "TEMPERATURE", "DATE")]
```

Fix classes
```{r classes}
seus_lookdown_red$LENGTH <- as.numeric(seus_lookdown_red$LENGTH)
seus_lookdown_red$LATITUDE <- as.numeric(seus_lookdown_red$LATITUDE)
seus_lookdown_red$LONGITUDE <- as.numeric(seus_lookdown_red$LONGITUDE)
seus_lookdown_red$TEMPERATURE <- as.numeric(seus_lookdown_red$TEMPERATURE)
seus_lookdown_red$DATE <- as.Date(seus_lookdown_red$DATE, format = "%m-%d-%Y")
neus_lookdown_red$LENGTH <- as.numeric(neus_lookdown_red$LENGTH)
neus_lookdown_red$LATITUDE <- as.numeric(neus_lookdown_red$LATITUDE)
neus_lookdown_red$LONGITUDE <- as.numeric(neus_lookdown_red$LONGITUDE)
neus_lookdown_red$TEMPERATURE <- as.numeric(neus_lookdown_red$TEMPERATURE)
neus_lookdown_red$DATE <- as.Date(neus_lookdown_red$DATE)
```

Bind tables.
```{r bind}
glf_lookdown_red.dt <- as.data.table(glf_lookdown_red)
seus_lookdown_red.dt <- as.data.table(seus_lookdown_red)
neus_lookdown_red.dt <- as.data.table(neus_lookdown_red)
lookdown_table <- rbind(glf_lookdown_red, neus_lookdown_red, seus_lookdown_red)
```
