---
title: "R Notebook"
output: Max/Min Latitude
---

Goal: Find the maximum and minimum latitude for each species for each year.

```{r setup}
load("lookdown_table.RData")

library(dplyr)
library(data.table)
library(stringr)
library(tibble)
library(ggplot2)
library(lubridate)

#Sampled in Gulf 1984-2018
#Sampled in seus 1989-2018
#Sampled in neus 1968-2018
```

Add a year and month column.
```{r add columns}
lookdown_table[ , YEAR := year(DATE)]
lookdown_table[ , MONTH := month(DATE)]
```

Add max/min latitude for year.
```{r lat}
lookdown_table[ , MAX_LAT := max(LATITUDE), by = YEAR]
lookdown_table[ , MIN_LAT := min(LATITUDE), by = YEAR]
```

Add a season column.
```{r season}
lookdown_table$MONTH <- as.numeric(lookdown_table$MONTH)
lookdown_table[ , SEASON := "spring"]
lookdown_table[MONTH>6, SEASON := "fall"]
```

Season max/min
```{r}
lookdown_table[ , MAX_SEA_LAT := max(LATITUDE), by = .(YEAR, SEASON)]
lookdown_table[ , MIN_SEA_LAT := min(LATITUDE), by = .(YEAR, SEASON)]
lookdown_table$MAX_SEA_LAT <- as.numeric(lookdown_table$MAX_SEA_LAT)
lookdown_table$MIN_SEA_LAT <- as.numeric(lookdown_table$MIN_SEA_LAT)

lookdown_table2 <- lookdown_table[YEAR>=1989]
```

```{r}
#fall maximimums will be higher than spring
ggplot(lookdown_table2, aes(x=YEAR, y=MAX_SEA_LAT, color=SEASON)) +
  geom_point() +
  theme_classic()

#spring minumims will be lower than fall
ggplot(lookdown_table2, aes(x=YEAR, y=MIN_SEA_LAT, color=SEASON)) +
  geom_point() +
  theme_classic()
```

Graph year vs. max/min.
```{r graph}
#hypothesis: max and min lat will both increase, assuming ocean temps are increasing over the years
ggplot(aes(x=YEAR, y=MAX_LAT), data = lookdown_table) +
  geom_point() +
  geom_smooth(method=lm) +
  theme_classic()

ggplot(aes(x=YEAR, y=MIN_LAT), data = lookdown_table) +
  geom_point() +
  geom_smooth(method=lm) +
  theme_classic()
```

Some other graphs...
```{r}
#max temp will increase over time
lookdown_table2[ , MAX_TEMP := max(TEMPERATURE, na.rm = T), by = YEAR]
#gets rid of NAs 

ggplot(aes(x=YEAR, y=MAX_TEMP), data = lookdown_table2) +
  geom_point() +
  geom_smooth(method=lm) +
  theme_classic() #max temp that species is found over time

lookdown_table[ , AVG_LEN := mean(LENGTH), by = YEAR]

ggplot(aes(x=YEAR, y=AVG_LEN), data = lookdown_table) +
  geom_point() +
  geom_smooth(method=lm) +
  theme_classic()
```

Make model for data
```{r model}
lookdown_model <- lm(MAX_SEA_LAT~YEAR, data = lookdown_table)
summary(lookdown_model)
# maximum season latitude = -.8.2e-2 * year + 2e+02
# good p-value, bad r2

lookdown_spring_model <- lm(MAX_SEA_LAT~YEAR, data = lookdown_table2[SEASON=="spring"])
summary(lookdown_spring_model)

lookdown_fall_model <- lm(MAX_SEA_LAT~YEAR, data = lookdown_table2[SEASON=="fall"])
summary(lookdown_fall_model)
```

LAt vs Length
```{r}
ggplot(lookdown_table2, aes(x=LATITUDE, y=LENGTH)) +
  geom_point() +
  geom_smooth(method=lm) +
  theme_classic()

```

Model for lat vs len
```{r}
lookdown_len_model <- lm(LENGTH~LATITUDE, data = lookdown_table)
summary(lookdown_len_model)
#length = -2.8905 * latitude + 230.76750
#p-value = 2.2e-16
#R2 = 0.01234
```

