---
title: "R Notebook"
output: Species Comparisons
---

Goal: Compare the lat vs length of all 7 species of interest.

```{r}
load("blackSB_table.RData")
load("lookdown_table.RData")
load("boxcrab_table.RData")
load("puffer_table.RData")
load("LFsquid_table.RData")
load("hammerhead_table.RData")
load("sunfish_table.RData")
library(dplyr)
library(data.table)
library(stringr)
library(tibble)
library(ggplot2)
library(lubridate)
```

Remove exess years
```{r}
#cut off before 1989 b/c seus starts last (1989)
blackSB_table[ , YEAR := year(DATE)]
blackSB_table[ , MONTH := month(DATE)]
blackSB_table$MONTH <- as.numeric(blackSB_table$MONTH)
blackSB_table[ , SEASON := "spring"]
blackSB_table[MONTH>6, SEASON := "fall"]
blackSB_table2 <- blackSB_table[YEAR>1989]

lookdown_table[ , YEAR := year(DATE)]
lookdown_table[ , MONTH := month(DATE)]
lookdown_table$MONTH <- as.numeric(lookdown_table$MONTH)
lookdown_table[ , SEASON := "spring"]
lookdown_table[MONTH>6, SEASON := "fall"]
lookdown_table2 <- lookdown_table[YEAR>1989]

boxcrab_table[ , YEAR := year(DATE)]
boxcrab_table[ , MONTH := month(DATE)]
boxcrab_table$MONTH <- as.numeric(boxcrab_table$MONTH)
boxcrab_table[ , SEASON := "spring"]
boxcrab_table[MONTH>6, SEASON := "fall"]
boxcrab_table2 <- boxcrab_table[YEAR>1989]

puffer_table[ , YEAR := year(DATE)]
puffer_table[ , MONTH := month(DATE)]
puffer_table$MONTH <- as.numeric(puffer_table$MONTH)
puffer_table[ , SEASON := "spring"]
puffer_table[MONTH>6, SEASON := "fall"]
puffer_table2 <- puffer_table[YEAR>1989]

LFsquid_table[ , YEAR := year(DATE)]
LFsquid_table[ , MONTH := month(DATE)]
LFsquid_table$MONTH <- as.numeric(LFsquid_table$MONTH)
LFsquid_table[ , SEASON := "spring"]
LFsquid_table[MONTH>6, SEASON := "fall"]
LFsquid_table2 <- LFsquid_table[YEAR>1989]

hammerhead_table[ , YEAR := year(DATE)]
hammerhead_table[ , MONTH := month(DATE)]
hammerhead_table$MONTH <- as.numeric(hammerhead_table$MONTH)
hammerhead_table[ , SEASON := "spring"]
hammerhead_table[MONTH>6, SEASON := "fall"]
hammerhead_table2 <- hammerhead_table[YEAR>1989]

sunfish_table[ , YEAR := year(DATE)]
sunfish_table[ , MONTH := month(DATE)]
sunfish_table$MONTH <- as.numeric(sunfish_table$MONTH)
sunfish_table[ , SEASON := "spring"]
sunfish_table[MONTH>6, SEASON := "fall"]
sunfish_table2 <- sunfish_table[YEAR>1989]
```

Lat vs length graphs
```{r}
ggplot(blackSB_table2, aes(x=LATITUDE, y=LENGTH, color=SEASON)) +
  geom_point() +
  geom_smooth(method=lm) +
  theme_classic()

ggplot(lookdown_table2, aes(x=LATITUDE, y=LENGTH, color=SEASON)) +
  geom_point() +
  geom_smooth(method=lm) +
  theme_classic()

ggplot(boxcrab_table2, aes(x=LATITUDE, y=LENGTH, color=SEASON)) +
  geom_point() +
  geom_smooth(method=lm) +
  theme_classic()

ggplot(puffer_table2, aes(x=LATITUDE, y=LENGTH, color=SEASON)) +
  geom_point() +
  geom_smooth(method=lm) +
  theme_classic()

ggplot(LFsquid_table2, aes(x=LATITUDE, y=LENGTH, color=SEASON)) +
  geom_point() +
  geom_smooth(method=lm) +
  theme_classic()

ggplot(hammerhead_table2, aes(x=LATITUDE, y=LENGTH, color=SEASON)) +
  geom_point() +
  geom_smooth(method=lm) +
  theme_classic()

ggplot(sunfish_table2, aes(x=LATITUDE, y=LENGTH, color=SEASON)) +
  geom_point() +
  geom_smooth(method=lm) +
  theme_classic()
```

Models for each of the above graphs.
```{r}
blackSB_model <- lm(LENGTH~LATITUDE*SEASON, data = blackSB_table2)
summary(blackSB_model)
#y=mx+b
#length = m * lat + b
#SPRING length = 6.0170 * lat -178.5545
#FALL length = 8.1410 * lat -133.3204

lookdown_model <- lm(LENGTH~LATITUDE*SEASON, data = lookdown_table2)
summary(lookdown_model)
#SPRING length = 8.34391 * lat -271.32277
#FALL length = -2.87965 * lat + 230.73128

boxcrab_model <- lm(LENGTH~LATITUDE*SEASON, data = boxcrab_table2)
summary(boxcrab_model)
#SPRING length = 5.5571 * lat - 160.57034
#FALL len = 0.9611 * lat + 91.9180

puffer_model <- lm(LENGTH~LATITUDE*SEASON, data = puffer_table2)
summary(puffer_model)
#SPRING len = -4.7080 * lat + 167.7223
#FALL len = -0.7644 * lat + 164.8941

LFsquid_model <- lm(LENGTH~LATITUDE*SEASON, data = LFsquid_table2)
summary(LFsquid_model)
#SPRING len = 0.50409 * lat - 16.15152
#FALL len = 2.36452 * lat + 15.89981

hammerhead_model <- lm(LENGTH~LATITUDE*SEASON, data = hammerhead_table2)
summary(hammerhead_model)
#SPRING len = 14.8621 * lat - 445.0967
#FALL len = -1.9011 * lat + 195.7880

sunfish_model <- lm(LENGTH~LATITUDE*SEASON, data = sunfish_table2)
summary(sunfish_model)
#SPRING len = 645.94 * lat - 23133.09
#FALL len = -19.85 * lat + 2244.06
```

